apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-{{ app_name }}
  namespace: ns-{{ app_name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ app_name }}.{{ lb_ip }}.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-{{ app_name }}
            port:
              number: 80
